### ISSUE TITLE
Warning: Unable to install the app in this location

### ISSUE THREAD

**Issue by MarcusMoeller** [kemenaran/mattermost_ynh#5]
I am trying to install Mattermost on my Yunohost instance. I have selected my main domain as installation target but get an error like:

Warning: Unable to install the app in this location

Any ideas?

**Comment by kemenaran** [comment]
@MarcusMoeller this could be because for now this package requires Mattermost to be installed in the top-directory, at the root of the domain (subdomains are not supported yet).

So probably Yunohost detects that installing Mattermost at the root of your main domain would make it inaccessible – and prevents you to do so.

I created an issue to allow installation in subdomains (#8). As a workaround, does it work with another domain? For instance you could create a sub-domain of your main Yunohost domain (like `chat.mydomain.com`), and install it from there.
